### PR TITLE
Updated the README.md

### LINKED ISSUE #66: [docs]Improving the README.md
### Category of documentation update

I would like to make some changes to structuring of add some features to make the README.md more appealing

I would like to be assigned to the issue if approved

### Describe the change you think might work

+ Better paragraph structure
+ Better formatting
+ Visual badges
+ emojis
+ etc

### PR DESCRIPTION
**Pull request by the-amazing-atharva**
## Fixes Issue

This PR fixes the following issues:

closes #66 

Made all the changes listed in #66 and added some extra features

### CODE REVIEW

**Review by kedaroo — APPROVED** [review]

**Review by kedaroo — APPROVED** [review]
This looks great! It is GTG. 🚀

**Comment by the-amazing-atharva** [comment]
> This looks great! It is GTG. 🚀

Thanks!

**Review by siddhigate — APPROVED** [review]
Looks awesome🚀 Thanks @the-amazing-atharva  for your contribution!

**Comment by the-amazing-atharva** [comment]
@siddhigate Thanks for the reply

Is there any other way to contribute to WeMakeDevs ??

Like any other opportunities apart from GitHub?

**Pull request merged**
